name: spotscriber_app
description: App for transcribing audio files (text conversion, diarization)

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  chaquopy: ^0.0.20
  path_provider: ^2.0.11 
  provider: ^6.1.2  # Ensure this version is compatible with Flutter 3.29+
  file_picker: ^6.1.1  

  english_words: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - ek_assets/images/


